Mailservice
ohtu2021satoja/SatojaREKO pull request #68
Opened 2021-06-22 12:35 UTC by silmish

Added few mailservice tweaks and endpoint for contact us page.

2021-06-22 19:12 UTC, NinaKWelch approved these changes

2021-06-23 07:39 UTC, ToxPuro requested changes
Could you remove .idea-files.
Good job! :)

2021-06-23 07:39 UTC, ToxPuro commented on client/src/services/mail.js
> +const newMessage = {
Probably doesn't need this anymore?

2021-06-23 07:39 UTC, ToxPuro commented on server/services/templates/eventReminderTemp.js
> +module.exports = {subject, message}
Is the vahvista tunnus because of copypaste or what?

2021-06-23 07:39 UTC, ToxPuro commented on server/services/templates/orderCancelTemp.js
> +    return (`<p>Paina alla olevaa vahvista nappia, vahvistaaksesi tunnuksen luomisen</p>\
Should you change this to be more appropriate to the message?

2021-06-23 07:40 UTC, ToxPuro commented on client/src/services/mail.js
> +const newMessage = {
Mean the newmessage object

2021-06-23 08:38 UTC, ToxPuro approved these changes
Great job!

2021-06-23 08:38 UTC, merged